### ISSUE TITLE
waque init Request failed with status code 401

### ISSUE THREAD

**Issue by andyxm** [yesmeck/waque#13]
E:\waque>waque init
Error: Request failed with status code 401
    at createError (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/core/createError.js:16:15)
    at settle (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (E:/Nodejs/node_global/node_modules/waque/node_modules/axios/lib/adapters/http.js
:202:11)

公司电脑没有问题，但是家里的电脑waque init 就报错
也登陆授权了

**Comment by yesmeck** [comment]
我reopen 了，不要重复提了。
