### ISSUE TITLE
Linux terminal login failed

### ISSUE THREAD

**Issue by coanor** [yesmeck/waque#24]
I'm using Linux command line to login yuque? there was no X11 install, the login failed:

```
request token timeout
```

Is it possible to login without UI?

**Comment by yesmeck** [comment]
问题还在吗？

**Comment by coanor** [comment]
我现在是 windows 上的 WSL，现在报告如下，估计是浏览器起不来导致的。一定要用浏览器么？

```
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn cmd.exe',
  path: 'cmd.exe',
  spawnargs: [
    '/c',
    'start',
    '""',
    '/b',
    'https://www.yuque.com/oauth2/authorize?client_id=8Jy5oKMnVHpiL1ci1CRV^&scope=repo%2Cdoc%2Cgroup^&code=0LfaylJ0io5KzVcJtENdwyQu4ARpENftuENVXHkh^&response_type=code^&timestamp=1648031352566^&sign=0AubN1fWrcNV7L370KVWeKKE5D0%3D'
  ]
}
```
